# Generated by Django 2.2 on 2022-06-28 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220628_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 17, 0, 17, 925527, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 16, 59, 47, 925527, tzinfo=utc)),
        ),
    ]
