# Generated by Django 2.2 on 2022-06-28 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220628_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 17, 0, 22, 690651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 16, 59, 52, 691645, tzinfo=utc)),
        ),
    ]
