# Generated by Django 2.2 on 2022-07-07 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220628_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 16, 51, 58, 134977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 16, 51, 48, 134977, tzinfo=utc)),
        ),
    ]
