# Generated by Django 2.2 on 2022-07-07 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220707_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 18, 0, 21, 296645, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 18, 0, 11, 297643, tzinfo=utc)),
        ),
    ]
